# An image with our added services
image:
  file: .gitpod.Dockerfile

tasks:
  - name: Packages
    init: |
      (cd application/backend && npm i)
      (cd application/frontend && npm i)
      (cd application/common/elsa-constants && npm i)
      (cd application/common/elsa-types && npm i)
      gp sync-await database
      (cd application/backend && npm run edgetypes)
      (cd application/frontend && npm run dev:build)

  - name: Database
    init: >
      cd application/backend &&
      edgedb project init --non-interactive &&
      gp sync-done database

ports:
  - name: Frontend
    description: Port 3000 for the frontend
    port: 3000
    onOpen: open-browser

  - name: Database UI
    description: Port 10701 for the frontend
    port: 10701
    onOpen: open-preview
