import { GetObjectCommand, S3Client } from "@aws-sdk/client-s3";
import * as readline from "node:readline";
import { Readable } from "stream";

type DistributedMapManifest = {
  DestinationBucket: string;
  MapRunArn: string;
  ResultFiles: {
    FAILED: { Key: string; Size: number }[];
    PENDING: { Key: string; Size: number }[];
    SUCCEEDED: { Key: string; Size: number }[];
  };
};

/**
 * Async iterator that reads from an S3 MapRun JSON manifest and returns
 * the data as a stream of objects.
 * NOTE: this is assuming the output is a ResultWriter of type JSONL
 * (lines of individual JSON). Not a standalone JSON array.
 *
 * @param s3Client
 * @param manifestBucket
 * @param manifestKey
 */
export async function* getCopierMapRunManifestEntries(
  s3Client: S3Client,
  manifestBucket: string,
  manifestKey: string,
): AsyncIterable<any> {
  // the manifest.json is generated by an AWS Steps DISTRIBUTED map and shows the results
  // of all the individual map run parts
  const getManifestResult = await s3Client.send(
    new GetObjectCommand({
      Bucket: manifestBucket,
      Key: manifestKey,
    }),
  );

  if (!getManifestResult.Body) {
    throw new Error("Could not find manifest");
  }

  const manifest: DistributedMapManifest = JSON.parse(
    await getManifestResult.Body.transformToString(),
  );

  // A sample manifest
  // {
  //  "DestinationBucket":"elsa-data-tmp",
  //  "MapRunArn":"arn:aws:states:ap-southeast-2:12345678:mapRun:CopyOutStateMachineABCD/4474d22f-4056-30e3-978c-027016edac90:0c17ffd6-e8ad-44c0-a65b-a8b721007241",
  //  "ResultFiles":{
  //     "FAILED":[],
  //     "PENDING":[],
  //     "SUCCEEDED":[{"Key":"copy-out-test-working/a6faea86c066cd90/1-objects-to-copy.tsv/0c17ffd6-e8ad-44c0-a65b-a8b721007241/SUCCEEDED_0.json",
  //                   "Size":2887}]}}

  if (!manifest.ResultFiles)
    throw new Error(
      "AWS Steps Distributed map manifest.json is missing ResultFiles",
    );

  if (
    !Array.isArray(manifest.ResultFiles.PENDING) ||
    !Array.isArray(manifest.ResultFiles.FAILED) ||
    !Array.isArray(manifest.ResultFiles.SUCCEEDED)
  )
    throw new Error(
      "AWS Steps Distributed map manifest.json is missing an expected array for PENDING, FAILED or SUCCEEDED",
    );

  if (manifest.ResultFiles.PENDING.length > 0)
    throw new Error(
      "AWS Steps Distributed map manifest.json indicates there are PENDING results which is not a state we are expecting",
    );

  for (const s of manifest.ResultFiles.SUCCEEDED) {
    const getSuccessCommand = new GetObjectCommand({
      Bucket: manifestBucket,
      Key: s.Key,
    });

    const getSuccessResult = await s3Client.send(getSuccessCommand);

    if (!getSuccessResult.Body) continue;

    const rl = readline.createInterface(
      Readable.fromWeb(getSuccessResult.Body.transformToWebStream()),
    );

    for await (const jsonLineString of rl) {
      yield JSON.parse(jsonLineString);
    }

    return [];
  }
}
