// Feature flags are used to communicate between config/backend/frontend giving an
// indication of which functionality is enabled.
// For instance, if Elsa Data is started with no AWS credentials, then some AWS features
// must be disabled and will disappear from the feature array.

//export const FEATURE_DATA_SHARING_HTSGET = "tlOFo";
//export const FEATURE_DATA_SHARING_AWS_ACCESS_POINT = "IHlkZ";

//export const FEATURE_DATA_SHARING_COPY_OUT = "IFQWG";

// export const FEATURE_DATA_SHARING_GCP_IAM = "vacuX";

export const FEATURE_RELEASE_COHORT_CONSTRUCTOR = "fOuKh";

export const FEATURE_RELEASE_DATA_EGRESS_VIEWER = "ryUMa";

export const FEATURE_RELEASE_CONSENT_DISPLAY = "jnMqv";

// these are a set of unique feature codes generated by a random string generator
// take from this list as we add feature codes above
/*





vStbC
WkfVr
LQPOz
rKwfe
ngWOq
molHs
ANiTq
SxvUW
LIVdt
HeNiN
iRXpZ
qriKY
crqpw
YsJLe
DscKm
BaUfn
hyjid
npwkZ
pRCjJ
RRbdy
rnJIQ
yxsKA
ewlNP
AkNjP
VQJgS
kybVv
NEQjS
pLAqe
EKJds
NLJey
kTcZi
MqMZL
msWWy
VChsI
Yayuj
iPnPg
oHUtL
YpTCI
QvBLX
JbOGy
 */
