export const ALLOWED_CHANGE_USER_PERMISSION = "sMcBG";
export const ALLOWED_CREATE_NEW_RELEASE = "ryIAD";
export const ALLOWED_OVERALL_ADMIN_VIEW = "PtJMH";
export const ALLOWED_DATASET_UPDATE = "UGtOI";

// these are a set of unique "allowed" feature codes generated by a random string generator
// take from this list as we add feature codes above
/*
UGtOI
AKuLu
UlUgI
JgsNF
WOAad
nLKPa
QdknH
MIvzY
OufdH
yVcCw
EpGfn
ysMDM
aulsM
rTGVr
bZrMx
yNWfr
LPsfF
vhVKk
QXvAY
aleCe
YWauX
wAZVF
LBdWH
tLbWe
XPodI
YQkMR
MrkJx
HwFPE
jzNXq
TMean
IFQlk
SEytp
NkPup
dkDTQ
HKluL
aCLzq
SxHgt
hHVXm
eobug
njbNN
dOErh
aLtIq
tQtaM
XxJer
DtNhS
ccgOu
cGnLs
bTRrv
ciWHa
WKtmc
 */
