export const ALLOWED_CHANGE_ADMINS = "sMcBG";
export const ALLOWED_CREATE_NEW_RELEASES = "ryIAD";

/**
 * An array that maps the above "allowed" flags into strings that can be printed.
 * Will be used purely for dev/debug purposes.
 */
export function debugAllowedDescription(allowed: string) {
  switch (allowed) {
    case ALLOWED_CHANGE_ADMINS:
      return "change admins";
    case ALLOWED_CREATE_NEW_RELEASES:
      return "create new releases";
    default:
      return `unknown 'allowed' with code ${allowed}`;
  }
}

// these are a set of unique "allowed" feature codes generated by a random string generator
// take from this list as we add feature codes above
/*
PtJMH
UGtOI
AKuLu
UlUgI
JgsNF
WOAad
nLKPa
QdknH
MIvzY
OufdH
yVcCw
EpGfn
ysMDM
aulsM
rTGVr
bZrMx
yNWfr
LPsfF
vhVKk
QXvAY
aleCe
YWauX
wAZVF
LBdWH
tLbWe
XPodI
YQkMR
MrkJx
HwFPE
jzNXq
TMean
IFQlk
SEytp
NkPup
dkDTQ
HKluL
aCLzq
SxHgt
hHVXm
eobug
njbNN
dOErh
aLtIq
tQtaM
XxJer
DtNhS
ccgOu
cGnLs
bTRrv
ciWHa
WKtmc
tlOFo
IHlkZ
vacuX
IFQWG
fOuKh
ryUMa
jnMqv
vStbC
WkfVr
LQPOz
rKwfe
ngWOq
molHs
ANiTq
SxvUW
LIVdt
HeNiN
iRXpZ
qriKY
crqpw
YsJLe
DscKm
BaUfn
hyjid
npwkZ
pRCjJ
RRbdy
rnJIQ
yxsKA
ewlNP
AkNjP
VQJgS
kybVv
NEQjS
pLAqe
EKJds
NLJey
kTcZi
MqMZL
msWWy
VChsI
Yayuj
iPnPg
oHUtL
YpTCI
QvBLX
JbOGy
 */
