name: Docker Image Build

on:
  push:
    branches:
      - "dev"
    tags:
      - '*'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to GHCR
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: andrewpatto
          password: ${{ secrets.ELSA_DATA_PUBLISH_DOCKER_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: application
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ghcr.io/umccr/elsa-data:${{ github.ref_name }}
            ghcr.io/umccr/elsa-data:${{ github.sha }}
          build-args: |
            ELSA_DATA_VERSION=${{ github.ref_name }}
            GITHUB_SHA=${{ github.sha }}
