name: CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # get the code
      - uses: actions/checkout@v4

      # install software we will use
      - uses: oven-sh/setup-bun@v2

      # backend compile
      # quick check to make sure code is not fundamentally broken
      - name: Source compiles
        run: bunx tsc
        working-directory: application/backend
