name: CI

on:
  # Triggers the workflow on push or pull request events but not for our feature branches
  #push:
  #  branches: ["dev", "main"]
  #pull_request:
  #  branches: ["dev", "main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # get the code
      - uses: actions/checkout@v4

      # install software we will use
      - uses: oven-sh/setup-bun@v2
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "npm"
          cache-dependency-path: "**/package-lock.json"
