name: CI

on:
  # Triggers the workflow on push or pull request events but not for our feature branches
  push:
    branches: ["dev", "main"]
  pull_request:
    branches: ["dev", "main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Check out repo
      - uses: actions/checkout@v3

      # setup NodeJs
      - uses: actions/setup-node@v3
        with:
          node-version: 18

      # setup all our packages (with caching)
      - uses: bahmutov/npm-install@v1
        with:
          working-directory: |
            application/common/elsa-constants
            application/common/elsa-types
            application/backend
            application/frontend
          install-command: npm ci --install-links=false

      # Install an EdgeDb for use by the tests
      #- uses: edgedb/setup-edgedb@8bc9e10005674ec772652b86e1fdd476e6462284
      #  with:
      #    # Trying nightly to get around some bugs.. pin when we can
      #    cli-version: nightly
      #    server-version: nightly
      #    project-dir: application/backend

      #- name: Generate EdgeDb types
      #  run: npm run edgetypes
      #  notWorking-directory: application/backend
